Update defaults/main.yml
Reuse https://app.radicle.xyz/nodes/seed.radicle.garden/rad%3Az2chD7Kt74JwEMafxTooxN7MaeYtK/tree/c4de1df58aedf504f5395668aa8507a17c193364/defaults/main.yml

Signed-off-by: Suguru Hirahara <did:key:z6MkvVZk1A3KBApWJXv2Ju4H14ErDfRGxh8zxdXSZ4vACDg5>

diff --git a/defaults/main.yml b/defaults/main.yml
--- a/defaults/main.yml
+++ b/defaults/main.yml
@@ -1,32 +1,221 @@
+# SPDX-FileCopyrightText: 2023, 2024 Nikita Chernyi
+# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
 # SPDX-FileCopyrightText: 2024 Bergrübe
+# SPDX-FileCopyrightText: 2024 Sergio Durigan Junior
+# SPDX-FileCopyrightText: 2025 MASH project contributors
+# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
 #
 # SPDX-License-Identifier: AGPL-3.0-or-later
 
 ---
-
 # Project source code URL: https://github.com/apache/couchdb
 
 couchdb_enabled: true
+
 couchdb_identifier: couchdb
+couchdb_base_path: "/{{ couchdb_identifier }}"
+couchdb_data_path: "{{ couchdb_base_path }}/data"
+
+# renovate: datasource=docker depName=library/couchdb versioning=semver
+couchdb_version: 3.5.1
+
+couchdb_uid: ""
+couchdb_gid: ""
+
+# The scheme used for serving CouchDB.
+couchdb_scheme: https
+
+# The hostname at which CouchDB is served.
 couchdb_hostname: ""
 
-couchdb_version: "3.4.3"
+# The path at which CouchDB is served.
+# This value must either be `/` or not end with a slash (e.g. `/couchdb`).
+#
+# Hosting CouchDB under a subpath does not seem to be possible due to CouchDB's
+# technical limitations.
+couchdb_path_prefix: /
+
+couchdb_container_image: "{{ couchdb_container_image_registry_prefix }}couchdb:{{ couchdb_container_image_tag }}"
+couchdb_container_image_tag: "{{ couchdb_version }}"
+couchdb_container_image_registry_prefix: "{{ couchdb_container_image_registry_prefix_upstream }}"
+couchdb_container_image_registry_prefix_upstream: "{{ couchdb_container_image_registry_prefix_upstream_default }}"
+couchdb_container_image_registry_prefix_upstream_default: docker.io/
+couchdb_container_image_force_pull: "{{ couchdb_container_image.endswith(':latest') }}"
+
+# The base container network. It will be auto-created by this role if it doesn't exist already.
+couchdb_container_network: "{{ couchdb_identifier }}"
+
+# Control if the container network is deleted on uninstalling.
+couchdb_container_network_deletion_enabled: true
+
+# Specify how the container publishes its HTTP port (as defined by `couchdb_container_http_port`).
+#
+# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:2586"), or empty string to not expose.
+couchdb_container_http_host_bind_port: ""
+
+# The port number in the container
+couchdb_container_http_port: 5984
+
+# A list of additional container networks that the container would be connected to.
+# The role does not create these networks, so make sure they already exist.
+# Use this to expose this container to another reverse proxy, which runs in a different container network.
+couchdb_container_additional_networks: "{{ couchdb_container_additional_networks_auto + couchdb_container_additional_networks_custom }}"
+couchdb_container_additional_networks_auto: []
+couchdb_container_additional_networks_custom: []
+
+# A list of additional "volumes" to mount in the container.
+# This list gets populated dynamically at runtime. You can provide a different default value,
+# if you wish to mount your own files into the container.
+# Contains definition objects like this: `{"type": "bind", "src": "/outside", "dst": "/inside", "options": "readonly"}.
+# See the `--mount` documentation for the `docker run` command.
+couchdb_container_additional_volumes: "{{ couchdb_container_additional_volumes_auto + couchdb_container_additional_volumes_custom }}"
+couchdb_container_additional_volumes_auto: []
+couchdb_container_additional_volumes_custom: []
+
+# couchdb_container_labels_traefik_enabled controls whether labels to assist a Traefik reverse-proxy will be attached to the container.
+# See `../templates/labels.j2` for details.
+#
+# To inject your own other container labels, see `couchdb_container_labels_additional_labels_custom`.
+couchdb_container_labels_traefik_enabled: true
+couchdb_container_labels_traefik_docker_network: "{{ couchdb_container_network }}"
+couchdb_container_labels_traefik_hostname: "{{ couchdb_hostname }}"
+# The path prefix must either be `/` or not end with a slash (e.g. `/couchdb`).
+couchdb_container_labels_traefik_path_prefix: "{{ couchdb_path_prefix }}"
+couchdb_container_labels_traefik_rule: "Host(`{{ couchdb_container_labels_traefik_hostname }}`){% if couchdb_container_labels_traefik_path_prefix != '/' %} && PathPrefix(`{{ couchdb_container_labels_traefik_path_prefix }}`){% endif %}"
+couchdb_container_labels_traefik_priority: 0
+couchdb_container_labels_traefik_entrypoints: web-secure
+couchdb_container_labels_traefik_tls: "{{ couchdb_container_labels_traefik_entrypoints != 'web' }}"
+couchdb_container_labels_traefik_tls_certResolver: default  # noqa var-naming
+
+# Controls which additional headers to attach to all HTTP requests.
+# To add your own custom request headers, use `couchdb_container_labels_traefik_additional_request_headers_custom`
+couchdb_container_labels_traefik_additional_request_headers: "{{ couchdb_container_labels_traefik_additional_request_headers_auto | combine(couchdb_container_labels_traefik_additional_request_headers_custom) }}"
+couchdb_container_labels_traefik_additional_request_headers_auto: {}
+couchdb_container_labels_traefik_additional_request_headers_custom: {}
+
+# Controls which additional headers to attach to all HTTP responses.
+# To add your own custom response headers, use `couchdb_container_labels_traefik_additional_response_headers_custom`
+couchdb_container_labels_traefik_additional_response_headers: "{{ couchdb_container_labels_traefik_additional_response_headers_auto | combine(couchdb_container_labels_traefik_additional_response_headers_custom) }}"
+couchdb_container_labels_traefik_additional_response_headers_auto: |
+  {{
+    {}
+    | combine ({'X-XSS-Protection': couchdb_http_header_xss_protection} if couchdb_http_header_xss_protection else {})
+    | combine ({'X-Content-Type-Options': couchdb_http_header_content_type_options} if couchdb_http_header_content_type_options else {})
+    | combine ({'Content-Security-Policy': couchdb_http_header_content_security_policy} if couchdb_http_header_content_security_policy else {})
+    | combine ({'Permissions-Policy': couchdb_http_header_permissions_policy} if couchdb_http_header_permissions_policy else {})
+    | combine ({'Strict-Transport-Security': couchdb_http_header_strict_transport_security} if couchdb_http_header_strict_transport_security and couchdb_container_labels_traefik_tls else {})
+  }}
+couchdb_container_labels_traefik_additional_response_headers_custom: {}
+
+# couchdb_container_labels_additional_labels contains a multiline string with additional labels to add to the container label file.
+# See `../templates/labels.j2` for details.
+# To add your own custom labels, use `couchdb_container_labels_additional_labels_custom`
+#
+# Example:
+# couchdb_container_labels_additional_labels_custom:
+#   - my.label=1
+#   - another.label="here"
+couchdb_container_labels_additional_labels: "{{ couchdb_container_labels_additional_labels_auto + couchdb_container_labels_additional_labels_custom }}"
+couchdb_container_labels_additional_labels_auto: []
+couchdb_container_labels_additional_labels_custom: []
+
+# A list of extra arguments to pass to the container (`docker create` command)
+couchdb_container_extra_arguments: "{{ couchdb_container_extra_arguments_auto + couchdb_container_extra_arguments_custom }}"
+couchdb_container_extra_arguments_auto: []
+couchdb_container_extra_arguments_custom: []
+
+# Specifies the value of the `X-XSS-Protection` header
+# Stops pages from loading when they detect reflected cross-site scripting (XSS) attacks.
+#
+# Learn more about it is here:
+# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
+# - https://portswigger.net/web-security/cross-site-scripting/reflected
+couchdb_http_header_xss_protection: "1; mode=block"
+
+# Specifies the value of the `X-Content-Type-Options` header.
+# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
+couchdb_http_header_content_type_options: nosniff
+
+# Specifies the value of the `Content-Security-Policy` header.
+# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
+couchdb_http_header_content_security_policy: frame-ancestors 'self'
+
+# Specifies the value of the `Permissions-Policy` header.
+# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy
+couchdb_http_header_permissions_policy: "{{ 'interest-cohort=()' if couchdb_floc_optout_enabled else '' }}"
+
+# Specifies the value of the `Strict-Transport-Security` header.
+# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
+couchdb_http_header_strict_transport_security: "max-age=31536000; includeSubDomains{{ '; preload' if couchdb_hsts_preload_enabled else '' }}"
+
+# Controls whether to send a "Permissions-Policy interest-cohort=();" header along with all responses
+#
+# Learn more about what it is here:
+# - https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea
+# - https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
+# - https://amifloced.org/
+#
+# Of course, a better solution is to just stop using browsers (like Chrome), which participate in such tracking practices.
+# See: `couchdb_http_header_permissions_policy`
+couchdb_floc_optout_enabled: true
+
+# Controls if HSTS preloading is enabled
+#
+# In its strongest and recommended form, the [HSTS policy](https://www.chromium.org/hsts) includes all subdomains, and
+# indicates a willingness to be "preloaded" into browsers:
+# `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`
+# For more information visit:
+# - https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
+# - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
+# - https://hstspreload.org/#opt-in
+# See: `couchdb_http_header_strict_transport_security`
+couchdb_hsts_preload_enabled: false
+
+# List of systemd services that the CouchDB systemd service depends on
+couchdb_systemd_required_services_list: "{{ couchdb_systemd_required_services_list_default + couchdb_systemd_required_services_list_auto + couchdb_systemd_required_services_list_custom }}"
+couchdb_systemd_required_services_list_default: "{{ [devture_systemd_docker_base_docker_service_name] if devture_systemd_docker_base_docker_service_name else [] }}"
+couchdb_systemd_required_services_list_auto: []
+couchdb_systemd_required_services_list_custom: []
+
+# List of systemd services that the CouchDB systemd service wants
+couchdb_systemd_wanted_services_list: "{{ couchdb_systemd_wanted_services_list_default + couchdb_systemd_wanted_services_list_auto + couchdb_systemd_wanted_services_list_custom }}"
+couchdb_systemd_wanted_services_list_default: []
+couchdb_systemd_wanted_services_list_auto: []
+couchdb_systemd_wanted_services_list_custom: []
+
+# Controls how long to wait for the container to stop gracefully before killing it.
+couchdb_container_stop_grace_time_seconds: "{{ devture_systemd_docker_base_container_stop_grace_time_seconds }}"
+
+# Controls how long the pre-start cleanup should wait for stale container-name release
+# before failing startup explicitly.
+couchdb_container_cleanup_timeout_seconds: "{{ devture_systemd_docker_base_container_cleanup_timeout_seconds }}"
+
+# Controls the delay between pre-start cleanup retries.
+couchdb_container_cleanup_retry_delay_seconds: "{{ devture_systemd_docker_base_container_cleanup_retry_delay_seconds }}"
+
+# Shell command used in the systemd pre-start phase to deterministically remove a stale
+# container and wait until Docker releases its name.
+couchdb_container_cleanup_command: |
+  i=0;
+  while [ "$i" -lt {{ couchdb_container_cleanup_timeout_seconds }} ]; do
+  {{ devture_systemd_docker_base_host_command_docker }} stop -t {{ couchdb_container_stop_grace_time_seconds }} {{ couchdb_identifier }} >/dev/null 2>&1 || true;
+  {{ devture_systemd_docker_base_host_command_docker }} rm -f {{ couchdb_identifier }} >/dev/null 2>&1 || true;
+  if {{ devture_systemd_docker_base_host_command_docker }} container inspect {{ couchdb_identifier }} >/dev/null 2>&1; then
+  i=$((i + 1));
+  sleep {{ couchdb_container_cleanup_retry_delay_seconds }};
+  continue;
+  fi;
+  if {{ devture_systemd_docker_base_host_command_docker }} info >/dev/null 2>&1; then
+  exit 0;
+  fi;
+  echo "Failed to query Docker daemon while cleaning up {{ couchdb_identifier }}" >&2;
+  exit 1;
+  done;
+  echo "Failed to remove stale container {{ couchdb_identifier }} after {{ couchdb_container_cleanup_timeout_seconds }} attempts" >&2;
+  exit 1
+
 # In mb, default is 1gb
 couchdb_tmp_size: 1000
-
-couchdb_uid: '5984'
-couchdb_gid: '5984'
-
-couchdb_base_path: "/{{ couchdb_identifier }}"
-
-# A list of additional "mounts" to be mounted in the container.
-# Contains definition objects like this:
-# couchdb_container_additional_mounts:
-# - "type=bind|volume|tmpfs,source=/outside,target=/inside,readonly,bind-propagation=slave"
-couchdb_container_additional_mounts: []
-
-couchdb_config_path: "{{ couchdb_base_path }}/config"
-couchdb_data_path: "{{ couchdb_base_path }}/data"
 
 
 couchdb_admin_user: 'mash-admin'
@@ -50,9 +239,6 @@ couchdb_config_uuid: ''
 couchdb_config_single_node: true
 
 couchdb_config_extension: ''
-couchdb_container_labels_additional_labels: ''
-
-couchdb_container_network: '{{ couchdb_identifier }}'
 
 # See options: https://docs.couchdb.org/en/stable/config/logging.html#log/level
 couchdb_config_loglevel: error
@@ -99,36 +285,6 @@ couchdb_default_permissions:
     members:
         names: []
         roles: []
-
-couchdb_container_image: "{{ couchdb_container_image_registry_prefix }}couchdb:{{ couchdb_container_image_tag }}"
-couchdb_container_image_registry_prefix: "docker.io/"
-couchdb_container_image_tag: "{{ couchdb_version }}"
-couchdb_container_image_force_pull: "{{ couchdb_container_image.endswith(':latest') }}"
-
-############
-## SERVER ##
-############
-
-# List of systemd services that couchdb-api.service depends on
-couchdb_systemd_required_services_list: "{{ couchdb_systemd_required_services_list_default + couchdb_systemd_required_services_list_auto + couchdb_systemd_required_services_list_custom }}"
-couchdb_systemd_required_services_list_default: "{{ [devture_systemd_docker_base_docker_service_name] if devture_systemd_docker_base_docker_service_name else [] }}"
-couchdb_systemd_required_services_list_auto: []
-couchdb_systemd_required_services_list_custom: []
-
-
-couchdb_container_http_port: 5984
-
-# Controls whether the CouchDB container exposes its HTTP port (as defined by `couchdb_container_http_port`).
-#
-# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:8731"), or empty string to not expose.
-couchdb_container_http_host_bind_port: ""
-
-# A list of additional container networks that the container would be connected to.
-# The role does not create these networks, so make sure they already exist.
-# Use this to expose this container to another reverse proxy, which runs in a different container network.
-couchdb_container_additional_networks: "{{ couchdb_container_additional_networks_auto + couchdb_container_additional_networks_custom }}"
-couchdb_container_additional_networks_auto: []
-couchdb_container_additional_networks_custom: []
 
 # Specify the timezone
 couchdb_environment_variables_tz: UTC
